###########
##Plot 4##
###########


#Setup Working Directory
#Make sure this is correct before running code!!!
setwd('/Users/hhusain/Git_Repositories/datasciencecoursera/ExData_Plotting1')

###Get The Data If It Doesn't Exist, Uses The Script 'GetData.R', 
###which is located in the same root directory
if (!exists('filtered_p1dat')) {
        source('GetData.R')
}

###Bring In Source For Third Plot - Because It's Repeated Here
###Plot 3 is generated by a function which i defined in plot3.R
source('plot3.R')

#setup canvas
par(mfrow = c(2, 2))


with(filtered_p1dat,{ 
        #First Plot
        plot(DateTime, Global_active_power, 
             ylab =  'Global Active Power',
             pch = NA,
             lines(DateTime, Global_active_power))
        #Second Plot
        plot(DateTime, Voltage, 
             ylab =  'Voltage',
             xlab = 'datetime',
             pch = NA,
             lines(DateTime, Voltage))
        #Third Plot (Created a Function To Do This)
        CreatePlot3()
        #Fourth Plot
        plot(DateTime, Global_reactive_power, 
             xlab = 'datetime',
             pch = NA,
             lines(DateTime, Global_reactive_power))
})

dev.copy(png, file = 'plot4.png')
dev.off()
